apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: cnet-Nov11-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cnet-Nov11-test 
  name: cnet-Nov11-test
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: cnet-Nov11-test
    weight: 100 
